/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/estadisticas`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/roles`; params?: Router.UnknownInputParams; } | { pathname: `/admin/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `/caja/cuenta`; params?: Router.UnknownInputParams; } | { pathname: `/caja`; params?: Router.UnknownInputParams; } | { pathname: `/caja/registrar-pago`; params?: Router.UnknownInputParams; } | { pathname: `/caja/ventas`; params?: Router.UnknownInputParams; } | { pathname: `/cocina/detalle-pedido`; params?: Router.UnknownInputParams; } | { pathname: `/cocina`; params?: Router.UnknownInputParams; } | { pathname: `/cocina/marcar listo`; params?: Router.UnknownInputParams; } | { pathname: `/cocina/pedidos`; params?: Router.UnknownInputParams; } | { pathname: `/mesero/crear-pedido`; params?: Router.UnknownInputParams; } | { pathname: `/mesero/estado-pedido`; params?: Router.UnknownInputParams; } | { pathname: `/mesero`; params?: Router.UnknownInputParams; } | { pathname: `/mesero/mesas`; params?: Router.UnknownInputParams; } | { pathname: `/mesero/productos`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/estadisticas`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/roles`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/usuarios`; params?: Router.UnknownOutputParams; } | { pathname: `/caja/cuenta`; params?: Router.UnknownOutputParams; } | { pathname: `/caja`; params?: Router.UnknownOutputParams; } | { pathname: `/caja/registrar-pago`; params?: Router.UnknownOutputParams; } | { pathname: `/caja/ventas`; params?: Router.UnknownOutputParams; } | { pathname: `/cocina/detalle-pedido`; params?: Router.UnknownOutputParams; } | { pathname: `/cocina`; params?: Router.UnknownOutputParams; } | { pathname: `/cocina/marcar listo`; params?: Router.UnknownOutputParams; } | { pathname: `/cocina/pedidos`; params?: Router.UnknownOutputParams; } | { pathname: `/mesero/crear-pedido`; params?: Router.UnknownOutputParams; } | { pathname: `/mesero/estado-pedido`; params?: Router.UnknownOutputParams; } | { pathname: `/mesero`; params?: Router.UnknownOutputParams; } | { pathname: `/mesero/mesas`; params?: Router.UnknownOutputParams; } | { pathname: `/mesero/productos`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/estadisticas${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/roles${`?${string}` | `#${string}` | ''}` | `/admin/usuarios${`?${string}` | `#${string}` | ''}` | `/caja/cuenta${`?${string}` | `#${string}` | ''}` | `/caja${`?${string}` | `#${string}` | ''}` | `/caja/registrar-pago${`?${string}` | `#${string}` | ''}` | `/caja/ventas${`?${string}` | `#${string}` | ''}` | `/cocina/detalle-pedido${`?${string}` | `#${string}` | ''}` | `/cocina${`?${string}` | `#${string}` | ''}` | `/cocina/marcar listo${`?${string}` | `#${string}` | ''}` | `/cocina/pedidos${`?${string}` | `#${string}` | ''}` | `/mesero/crear-pedido${`?${string}` | `#${string}` | ''}` | `/mesero/estado-pedido${`?${string}` | `#${string}` | ''}` | `/mesero${`?${string}` | `#${string}` | ''}` | `/mesero/mesas${`?${string}` | `#${string}` | ''}` | `/mesero/productos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/estadisticas`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/roles`; params?: Router.UnknownInputParams; } | { pathname: `/admin/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `/caja/cuenta`; params?: Router.UnknownInputParams; } | { pathname: `/caja`; params?: Router.UnknownInputParams; } | { pathname: `/caja/registrar-pago`; params?: Router.UnknownInputParams; } | { pathname: `/caja/ventas`; params?: Router.UnknownInputParams; } | { pathname: `/cocina/detalle-pedido`; params?: Router.UnknownInputParams; } | { pathname: `/cocina`; params?: Router.UnknownInputParams; } | { pathname: `/cocina/marcar listo`; params?: Router.UnknownInputParams; } | { pathname: `/cocina/pedidos`; params?: Router.UnknownInputParams; } | { pathname: `/mesero/crear-pedido`; params?: Router.UnknownInputParams; } | { pathname: `/mesero/estado-pedido`; params?: Router.UnknownInputParams; } | { pathname: `/mesero`; params?: Router.UnknownInputParams; } | { pathname: `/mesero/mesas`; params?: Router.UnknownInputParams; } | { pathname: `/mesero/productos`; params?: Router.UnknownInputParams; };
    }
  }
}
